class BibleBook {
  final String name;
  final int chapters;
  final bool isOldTestament;
  final bool isNewTestament;
  final bool isDeuterocanonical;
  final int canonicalOrder;
  final int chronologicalOrder;
  final int? jewishOrder;
  final String genre;
  final String? hebrewGroup;
  final List<int> wordCountPerChapter;

  const BibleBook({
    required this.name,
    required this.chapters,
    required this.isOldTestament,
    required this.isNewTestament,
    this.isDeuterocanonical = false,
    required this.canonicalOrder,
    required this.chronologicalOrder,
    this.jewishOrder,
    required this.genre,
    this.hebrewGroup,
    this.wordCountPerChapter = const [],
  });
}

class BibleData {
  static const List<BibleBook> books = [
    // Ancien Testament - Torah
    BibleBook(
        name: 'Genèse',
        chapters: 50,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 1,
        chronologicalOrder: 1,
        jewishOrder: 1,
        genre: 'law',
        hebrewGroup: 'Torah'),
    BibleBook(
        name: 'Exode',
        chapters: 40,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 2,
        chronologicalOrder: 2,
        jewishOrder: 2,
        genre: 'law',
        hebrewGroup: 'Torah'),
    BibleBook(
        name: 'Lévitique',
        chapters: 27,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 3,
        chronologicalOrder: 3,
        jewishOrder: 3,
        genre: 'law',
        hebrewGroup: 'Torah'),
    BibleBook(
        name: 'Nombres',
        chapters: 36,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 4,
        chronologicalOrder: 4,
        jewishOrder: 4,
        genre: 'law',
        hebrewGroup: 'Torah'),
    BibleBook(
        name: 'Deutéronome',
        chapters: 34,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 5,
        chronologicalOrder: 5,
        jewishOrder: 5,
        genre: 'law',
        hebrewGroup: 'Torah'),
    // Neviim Rishonim (Premiers Prophètes)
    BibleBook(
        name: 'Josué',
        chapters: 24,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 6,
        chronologicalOrder: 6,
        jewishOrder: 6,
        genre: 'history',
        hebrewGroup: 'Neviim'),
    BibleBook(
        name: 'Juges',
        chapters: 21,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 7,
        chronologicalOrder: 7,
        jewishOrder: 7,
        genre: 'history',
        hebrewGroup: 'Neviim'),
    BibleBook(
        name: 'Ruth',
        chapters: 4,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 8,
        chronologicalOrder: 8,
        jewishOrder: 25,
        genre: 'history',
        hebrewGroup: 'Ketuvim'),
    BibleBook(
        name: '1 Samuel',
        chapters: 31,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 9,
        chronologicalOrder: 9,
        jewishOrder: 8,
        genre: 'history',
        hebrewGroup: 'Neviim'),
    BibleBook(
        name: '2 Samuel',
        chapters: 24,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 10,
        chronologicalOrder: 10,
        jewishOrder: 9,
        genre: 'history',
        hebrewGroup: 'Neviim'),
    BibleBook(
        name: '1 Rois',
        chapters: 22,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 11,
        chronologicalOrder: 11,
        jewishOrder: 10,
        genre: 'history',
        hebrewGroup: 'Neviim'),
    BibleBook(
        name: '2 Rois',
        chapters: 25,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 12,
        chronologicalOrder: 12,
        jewishOrder: 11,
        genre: 'history',
        hebrewGroup: 'Neviim'),
    // Ketuvim (Écrits) - Livres historiques
    BibleBook(
        name: '1 Chroniques',
        chapters: 29,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 13,
        chronologicalOrder: 13,
        jewishOrder: 35,
        genre: 'history',
        hebrewGroup: 'Ketuvim'),
    BibleBook(
        name: '2 Chroniques',
        chapters: 36,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 14,
        chronologicalOrder: 14,
        jewishOrder: 36,
        genre: 'history',
        hebrewGroup: 'Ketuvim'),
    BibleBook(
        name: 'Esdras',
        chapters: 10,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 15,
        chronologicalOrder: 15,
        jewishOrder: 37,
        genre: 'history',
        hebrewGroup: 'Ketuvim'),
    BibleBook(
        name: 'Néhémie',
        chapters: 13,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 16,
        chronologicalOrder: 16,
        jewishOrder: 38,
        genre: 'history',
        hebrewGroup: 'Ketuvim'),
    BibleBook(
        name: 'Esther',
        chapters: 10,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 17,
        chronologicalOrder: 17,
        jewishOrder: 33,
        genre: 'history',
        hebrewGroup: 'Ketuvim'),
    // Ketuvim - Livres poétiques et de sagesse
    BibleBook(
        name: 'Job',
        chapters: 42,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 18,
        chronologicalOrder: 18,
        jewishOrder: 28,
        genre: 'wisdom',
        hebrewGroup: 'Ketuvim'),
    BibleBook(
        name: 'Psaumes',
        chapters: 150,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 19,
        chronologicalOrder: 19,
        jewishOrder: 26,
        genre: 'wisdom',
        hebrewGroup: 'Ketuvim'),
    BibleBook(
        name: 'Proverbes',
        chapters: 31,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 20,
        chronologicalOrder: 20,
        jewishOrder: 27,
        genre: 'wisdom',
        hebrewGroup: 'Ketuvim'),
    BibleBook(
        name: 'Ecclésiaste',
        chapters: 12,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 21,
        chronologicalOrder: 21,
        jewishOrder: 31,
        genre: 'wisdom',
        hebrewGroup: 'Ketuvim'),
    BibleBook(
        name: 'Cantique des cantiques',
        chapters: 8,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 22,
        chronologicalOrder: 22,
        jewishOrder: 30,
        genre: 'wisdom',
        hebrewGroup: 'Ketuvim'),
    // Neviim Aharonim (Derniers Prophètes) - Grands prophètes
    BibleBook(
        name: 'Ésaïe',
        chapters: 66,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 23,
        chronologicalOrder: 23,
        jewishOrder: 12,
        genre: 'major_prophets',
        hebrewGroup: 'Neviim'),
    BibleBook(
        name: 'Jérémie',
        chapters: 52,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 24,
        chronologicalOrder: 24,
        jewishOrder: 13,
        genre: 'major_prophets',
        hebrewGroup: 'Neviim'),
    BibleBook(
        name: 'Lamentations',
        chapters: 5,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 25,
        chronologicalOrder: 25,
        jewishOrder: 32,
        genre: 'wisdom',
        hebrewGroup: 'Ketuvim'),
    BibleBook(
        name: 'Ézéchiel',
        chapters: 48,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 26,
        chronologicalOrder: 26,
        jewishOrder: 14,
        genre: 'major_prophets',
        hebrewGroup: 'Neviim'),
    BibleBook(
        name: 'Daniel',
        chapters: 12,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 27,
        chronologicalOrder: 27,
        jewishOrder: 34,
        genre: 'wisdom',
        hebrewGroup: 'Ketuvim'),
    // Neviim Aharonim - Les Douze (Petits Prophètes)
    BibleBook(
        name: 'Osée',
        chapters: 14,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 28,
        chronologicalOrder: 28,
        jewishOrder: 15,
        genre: 'minor_prophets',
        hebrewGroup: 'Neviim'),
    BibleBook(
        name: 'Joël',
        chapters: 3,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 29,
        chronologicalOrder: 29,
        jewishOrder: 16,
        genre: 'minor_prophets',
        hebrewGroup: 'Neviim'),
    BibleBook(
        name: 'Amos',
        chapters: 9,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 30,
        chronologicalOrder: 30,
        jewishOrder: 17,
        genre: 'minor_prophets',
        hebrewGroup: 'Neviim'),
    BibleBook(
        name: 'Abdias',
        chapters: 1,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 31,
        chronologicalOrder: 31,
        jewishOrder: 18,
        genre: 'minor_prophets',
        hebrewGroup: 'Neviim'),
    BibleBook(
        name: 'Jonas',
        chapters: 4,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 32,
        chronologicalOrder: 32,
        jewishOrder: 19,
        genre: 'minor_prophets',
        hebrewGroup: 'Neviim'),
    BibleBook(
        name: 'Michée',
        chapters: 7,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 33,
        chronologicalOrder: 33,
        jewishOrder: 20,
        genre: 'minor_prophets',
        hebrewGroup: 'Neviim'),
    BibleBook(
        name: 'Nahum',
        chapters: 3,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 34,
        chronologicalOrder: 34,
        jewishOrder: 21,
        genre: 'minor_prophets',
        hebrewGroup: 'Neviim'),
    BibleBook(
        name: 'Habacuc',
        chapters: 3,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 35,
        chronologicalOrder: 35,
        jewishOrder: 22,
        genre: 'minor_prophets',
        hebrewGroup: 'Neviim'),
    BibleBook(
        name: 'Sophonie',
        chapters: 3,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 36,
        chronologicalOrder: 36,
        jewishOrder: 23,
        genre: 'minor_prophets',
        hebrewGroup: 'Neviim'),
    BibleBook(
        name: 'Aggée',
        chapters: 2,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 37,
        chronologicalOrder: 37,
        jewishOrder: 24,
        genre: 'minor_prophets',
        hebrewGroup: 'Neviim'),
    BibleBook(
        name: 'Zacharie',
        chapters: 14,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 38,
        chronologicalOrder: 38,
        jewishOrder: 39,
        genre: 'minor_prophets',
        hebrewGroup: 'Neviim'),
    BibleBook(
        name: 'Malachie',
        chapters: 4,
        isOldTestament: true,
        isNewTestament: false,
        canonicalOrder: 39,
        chronologicalOrder: 39,
        jewishOrder: 29,
        genre: 'minor_prophets',
        hebrewGroup: 'Neviim'),

    // Nouveau Testament - Évangiles
    BibleBook(
        name: 'Matthieu',
        chapters: 28,
        isOldTestament: false,
        isNewTestament: true,
        canonicalOrder: 40,
        chronologicalOrder: 40,
        jewishOrder: null,
        genre: 'gospels'),
    BibleBook(
        name: 'Marc',
        chapters: 16,
        isOldTestament: false,
        isNewTestament: true,
        canonicalOrder: 41,
        chronologicalOrder: 41,
        jewishOrder: null,
        genre: 'gospels'),
    BibleBook(
        name: 'Luc',
        chapters: 24,
        isOldTestament: false,
        isNewTestament: true,
        canonicalOrder: 42,
        chronologicalOrder: 42,
        jewishOrder: null,
        genre: 'gospels'),
    BibleBook(
        name: 'Jean',
        chapters: 21,
        isOldTestament: false,
        isNewTestament: true,
        canonicalOrder: 43,
        chronologicalOrder: 43,
        jewishOrder: null,
        genre: 'gospels'),
    BibleBook(
        name: 'Actes',
        chapters: 28,
        isOldTestament: false,
        isNewTestament: true,
        canonicalOrder: 44,
        chronologicalOrder: 44,
        jewishOrder: null,
        genre: 'history'),
    // Nouveau Testament - Épîtres
    BibleBook(
        name: 'Romains',
        chapters: 16,
        isOldTestament: false,
        isNewTestament: true,
        canonicalOrder: 45,
        chronologicalOrder: 45,
        jewishOrder: null,
        genre: 'epistles'),
    BibleBook(
        name: '1 Corinthiens',
        chapters: 16,
        isOldTestament: false,
        isNewTestament: true,
        canonicalOrder: 46,
        chronologicalOrder: 46,
        jewishOrder: null,
        genre: 'epistles'),
    BibleBook(
        name: '2 Corinthiens',
        chapters: 13,
        isOldTestament: false,
        isNewTestament: true,
        canonicalOrder: 47,
        chronologicalOrder: 47,
        jewishOrder: null,
        genre: 'epistles'),
    BibleBook(
        name: 'Galates',
        chapters: 6,
        isOldTestament: false,
        isNewTestament: true,
        canonicalOrder: 48,
        chronologicalOrder: 48,
        jewishOrder: null,
        genre: 'epistles'),
    BibleBook(
        name: 'Éphésiens',
        chapters: 6,
        isOldTestament: false,
        isNewTestament: true,
        canonicalOrder: 49,
        chronologicalOrder: 49,
        jewishOrder: null,
        genre: 'epistles'),
    BibleBook(
        name: 'Philippiens',
        chapters: 4,
        isOldTestament: false,
        isNewTestament: true,
        canonicalOrder: 50,
        chronologicalOrder: 50,
        jewishOrder: null,
        genre: 'epistles'),
    BibleBook(
        name: 'Colossiens',
        chapters: 4,
        isOldTestament: false,
        isNewTestament: true,
        canonicalOrder: 51,
        chronologicalOrder: 51,
        jewishOrder: null,
        genre: 'epistles'),
    BibleBook(
        name: '1 Thessaloniciens',
        chapters: 5,
        isOldTestament: false,
        isNewTestament: true,
        canonicalOrder: 52,
        chronologicalOrder: 52,
        jewishOrder: null,
        genre: 'epistles'),
    BibleBook(
        name: '2 Thessaloniciens',
        chapters: 3,
        isOldTestament: false,
        isNewTestament: true,
        canonicalOrder: 53,
        chronologicalOrder: 53,
        jewishOrder: null,
        genre: 'epistles'),
    BibleBook(
        name: '1 Timothée',
        chapters: 6,
        isOldTestament: false,
        isNewTestament: true,
        canonicalOrder: 54,
        chronologicalOrder: 54,
        jewishOrder: null,
        genre: 'epistles'),
    BibleBook(
        name: '2 Timothée',
        chapters: 4,
        isOldTestament: false,
        isNewTestament: true,
        canonicalOrder: 55,
        chronologicalOrder: 55,
        jewishOrder: null,
        genre: 'epistles'),
    BibleBook(
        name: 'Tite',
        chapters: 3,
        isOldTestament: false,
        isNewTestament: true,
        canonicalOrder: 56,
        chronologicalOrder: 56,
        jewishOrder: null,
        genre: 'epistles'),
    BibleBook(
        name: 'Philémon',
        chapters: 1,
        isOldTestament: false,
        isNewTestament: true,
        canonicalOrder: 57,
        chronologicalOrder: 57,
        jewishOrder: null,
        genre: 'epistles'),
    BibleBook(
        name: 'Hébreux',
        chapters: 13,
        isOldTestament: false,
        isNewTestament: true,
        canonicalOrder: 58,
        chronologicalOrder: 58,
        jewishOrder: null,
        genre: 'epistles'),
    BibleBook(
        name: 'Jacques',
        chapters: 5,
        isOldTestament: false,
        isNewTestament: true,
        canonicalOrder: 59,
        chronologicalOrder: 59,
        jewishOrder: null,
        genre: 'epistles'),
    BibleBook(
        name: '1 Pierre',
        chapters: 5,
        isOldTestament: false,
        isNewTestament: true,
        canonicalOrder: 60,
        chronologicalOrder: 60,
        jewishOrder: null,
        genre: 'epistles'),
    BibleBook(
        name: '2 Pierre',
        chapters: 3,
        isOldTestament: false,
        isNewTestament: true,
        canonicalOrder: 61,
        chronologicalOrder: 61,
        jewishOrder: null,
        genre: 'epistles'),
    BibleBook(
        name: '1 Jean',
        chapters: 5,
        isOldTestament: false,
        isNewTestament: true,
        canonicalOrder: 62,
        chronologicalOrder: 62,
        jewishOrder: null,
        genre: 'epistles'),
    BibleBook(
        name: '2 Jean',
        chapters: 1,
        isOldTestament: false,
        isNewTestament: true,
        canonicalOrder: 63,
        chronologicalOrder: 63,
        jewishOrder: null,
        genre: 'epistles'),
    BibleBook(
        name: '3 Jean',
        chapters: 1,
        isOldTestament: false,
        isNewTestament: true,
        canonicalOrder: 64,
        chronologicalOrder: 64,
        jewishOrder: null,
        genre: 'epistles'),
    BibleBook(
        name: 'Jude',
        chapters: 1,
        isOldTestament: false,
        isNewTestament: true,
        canonicalOrder: 65,
        chronologicalOrder: 65,
        jewishOrder: null,
        genre: 'epistles'),
    BibleBook(
        name: 'Apocalypse',
        chapters: 22,
        isOldTestament: false,
        isNewTestament: true,
        canonicalOrder: 66,
        chronologicalOrder: 66,
        jewishOrder: null,
        genre: 'apocalyptic'),
  ];

  // Livres deutérocanoniques (Apocryphes)
  static const List<BibleBook> deuterocanonicalBooks = [
    BibleBook(
        name: 'Tobit',
        chapters: 14,
        isOldTestament: true,
        isNewTestament: false,
        isDeuterocanonical: true,
        canonicalOrder: 67,
        chronologicalOrder: 67,
        jewishOrder: null,
        genre: 'history'),
    BibleBook(
        name: 'Judith',
        chapters: 16,
        isOldTestament: true,
        isNewTestament: false,
        isDeuterocanonical: true,
        canonicalOrder: 68,
        chronologicalOrder: 68,
        jewishOrder: null,
        genre: 'history'),
    BibleBook(
        name: 'Sagesse',
        chapters: 19,
        isOldTestament: true,
        isNewTestament: false,
        isDeuterocanonical: true,
        canonicalOrder: 69,
        chronologicalOrder: 69,
        jewishOrder: null,
        genre: 'wisdom'),
    BibleBook(
        name: 'Siracide',
        chapters: 51,
        isOldTestament: true,
        isNewTestament: false,
        isDeuterocanonical: true,
        canonicalOrder: 70,
        chronologicalOrder: 70,
        jewishOrder: null,
        genre: 'wisdom'),
    BibleBook(
        name: 'Baruch',
        chapters: 6,
        isOldTestament: true,
        isNewTestament: false,
        isDeuterocanonical: true,
        canonicalOrder: 71,
        chronologicalOrder: 71,
        jewishOrder: null,
        genre: 'major_prophets'),
    BibleBook(
        name: '1 Maccabées',
        chapters: 16,
        isOldTestament: true,
        isNewTestament: false,
        isDeuterocanonical: true,
        canonicalOrder: 72,
        chronologicalOrder: 72,
        jewishOrder: null,
        genre: 'history'),
    BibleBook(
        name: '2 Maccabées',
        chapters: 15,
        isOldTestament: true,
        isNewTestament: false,
        isDeuterocanonical: true,
        canonicalOrder: 73,
        chronologicalOrder: 73,
        jewishOrder: null,
        genre: 'history'),
    BibleBook(
        name: 'Additions à Esther',
        chapters: 7,
        isOldTestament: true,
        isNewTestament: false,
        isDeuterocanonical: true,
        canonicalOrder: 74,
        chronologicalOrder: 74,
        jewishOrder: null,
        genre: 'history'),
    BibleBook(
        name: 'Additions à Daniel',
        chapters: 3,
        isOldTestament: true,
        isNewTestament: false,
        isDeuterocanonical: true,
        canonicalOrder: 75,
        chronologicalOrder: 75,
        jewishOrder: null,
        genre: 'history'),
  ];

  static BibleBook? getBook(String name) {
    try {
      // Rechercher d'abord dans les 66 livres canoniques
      return books.firstWhere(
        (book) => book.name.toLowerCase() == name.toLowerCase(),
      );
    } catch (e) {
      // Si non trouvé, rechercher dans les deutérocanoniques
      try {
        return deuterocanonicalBooks.firstWhere(
          (book) => book.name.toLowerCase() == name.toLowerCase(),
        );
      } catch (e) {
        return null;
      }
    }
  }

  static List<BibleBook> getAllBooks({bool includeApocrypha = false}) {
    if (includeApocrypha) {
      return [...books, ...deuterocanonicalBooks];
    }
    return books;
  }

  static List<BibleBook> getOldTestamentBooks() {
    return books.where((book) => book.isOldTestament).toList();
  }

  static List<BibleBook> getNewTestamentBooks() {
    return books.where((book) => book.isNewTestament).toList();
  }

  static List<BibleBook> getBooksByHebrewGroup(String group) {
    return books
        .where((b) => b.hebrewGroup == group)
        .toList()
      ..sort((a, b) => (a.jewishOrder ?? 999).compareTo(b.jewishOrder ?? 999));
  }

  static List<BibleBook> getGospelWritersBooks() {
    // Évangiles + Actes + Épîtres + Apocalypse
    final gospelWritersNames = [
      'Matthieu',
      'Marc',
      'Luc',
      'Jean',
      'Actes',
      'Romains',
      '1 Corinthiens',
      '2 Corinthiens',
      'Galates',
      'Éphésiens',
      'Philippiens',
      'Colossiens',
      '1 Thessaloniciens',
      '2 Thessaloniciens',
      '1 Timothée',
      '2 Timothée',
      'Tite',
      'Philémon',
      'Hébreux',
      'Jacques',
      '1 Pierre',
      '2 Pierre',
      '1 Jean',
      '2 Jean',
      '3 Jean',
      'Jude',
      'Apocalypse',
    ];
    return books.where((b) => gospelWritersNames.contains(b.name)).toList();
  }

  static bool isDeuterocanonical(String bookName) {
    return deuterocanonicalBooks.any((b) => b.name == bookName);
  }

  static int getTotalChapters(List<String> bookNames) {
    int total = 0;
    for (final name in bookNames) {
      final book = getBook(name);
      if (book != null) {
        total += book.chapters;
      }
    }
    return total;
  }
}
